site_name: Llama
site_url: https://frelerik.github.io/llama/
repo_name: Frelerik/llama
repo_url: https://github.com/Frelerik/llama

theme:
  name: material
  icon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    scheme: slate
    primary: red
    accent: orange

nav:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Usage: guide/usage.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences